/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as proxyOftSol from "./ProxyOFT.sol";
export type { proxyOftSol };
import type * as erc20 from "./erc20";
export type { erc20 };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as lzApp from "./lzApp";
export type { lzApp };
import type * as utils from "./utils";
export type { utils };
export type { BasicTokenSender } from "./BasicTokenSender";
export type { OFTAccessControlUpgradeable } from "./OFTAccessControlUpgradeable";
export type { OFTCoreUpgradeable } from "./OFTCoreUpgradeable";
