/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { EIP712, EIP712Interface } from "../../../contracts/erc20/EIP712";

const _abi = [
  {
    inputs: [],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class EIP712__factory {
  static readonly abi = _abi;
  static createInterface(): EIP712Interface {
    return new Interface(_abi) as EIP712Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): EIP712 {
    return new Contract(address, _abi, runner) as unknown as EIP712;
  }
}
