/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as draftIerc20PermitSol from "./draft-IERC20Permit.sol";
export { EIP712__factory } from "./EIP712__factory";
export { ERC20MinterBurnerPauserPermitForReplacement__factory } from "./ERC20MinterBurnerPauserPermitForReplacement__factory";
