/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IWMTR } from "../IWMTR";

export class IWMTR__factory {
  static connect(address: string, signerOrProvider: Signer | Provider): IWMTR {
    return new Contract(address, _abi, signerOrProvider) as IWMTR;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "wad",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
