/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface EIP712Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "_CACHED_CHAIN_ID"
      | "_CACHED_DOMAIN_SEPARATOR"
      | "_CACHED_THIS"
      | "_HASHED_NAME"
      | "_HASHED_VERSION"
      | "_TYPE_HASH"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "_CACHED_CHAIN_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_CACHED_DOMAIN_SEPARATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_CACHED_THIS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_HASHED_NAME",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_HASHED_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_TYPE_HASH",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "_CACHED_CHAIN_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_CACHED_DOMAIN_SEPARATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_CACHED_THIS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_HASHED_NAME",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_HASHED_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "_TYPE_HASH", data: BytesLike): Result;
}

export interface EIP712 extends BaseContract {
  connect(runner?: ContractRunner | null): EIP712;
  waitForDeployment(): Promise<this>;

  interface: EIP712Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  _CACHED_CHAIN_ID: TypedContractMethod<[], [bigint], "view">;

  _CACHED_DOMAIN_SEPARATOR: TypedContractMethod<[], [string], "view">;

  _CACHED_THIS: TypedContractMethod<[], [string], "view">;

  _HASHED_NAME: TypedContractMethod<[], [string], "view">;

  _HASHED_VERSION: TypedContractMethod<[], [string], "view">;

  _TYPE_HASH: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "_CACHED_CHAIN_ID"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "_CACHED_DOMAIN_SEPARATOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "_CACHED_THIS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "_HASHED_NAME"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "_HASHED_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "_TYPE_HASH"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
