/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ITimelockInterface extends Interface {
  getFunction(
    nameOrSignature: "consumeValue" | "consumeValuePreview" | "createAgreement"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgreementClaimed"
      | "AgreementCreated"
      | "AgreementFrozen"
      | "AgreementRescued"
      | "TimeLockFrozen"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "consumeValue",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "consumeValuePreview",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createAgreement",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "consumeValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "consumeValuePreview",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAgreement",
    data: BytesLike
  ): Result;
}

export namespace AgreementClaimedEvent {
  export type InputTuple = [
    agreementId: BigNumberish,
    beneficiary: AddressLike,
    asset: AddressLike,
    amount: BigNumberish,
    sender: AddressLike
  ];
  export type OutputTuple = [
    agreementId: bigint,
    beneficiary: string,
    asset: string,
    amount: bigint,
    sender: string
  ];
  export interface OutputObject {
    agreementId: bigint;
    beneficiary: string;
    asset: string;
    amount: bigint;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgreementCreatedEvent {
  export type InputTuple = [
    agreementId: BigNumberish,
    beneficiary: AddressLike,
    asset: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    agreementId: bigint,
    beneficiary: string,
    asset: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    agreementId: bigint;
    beneficiary: string;
    asset: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgreementFrozenEvent {
  export type InputTuple = [agreementId: BigNumberish, value: boolean];
  export type OutputTuple = [agreementId: bigint, value: boolean];
  export interface OutputObject {
    agreementId: bigint;
    value: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgreementRescuedEvent {
  export type InputTuple = [
    agreementId: BigNumberish,
    asset: AddressLike,
    originalBeneficiary: AddressLike,
    amount: BigNumberish,
    to: AddressLike
  ];
  export type OutputTuple = [
    agreementId: bigint,
    asset: string,
    originalBeneficiary: string,
    amount: bigint,
    to: string
  ];
  export interface OutputObject {
    agreementId: bigint;
    asset: string;
    originalBeneficiary: string;
    amount: bigint;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimeLockFrozenEvent {
  export type InputTuple = [value: boolean];
  export type OutputTuple = [value: boolean];
  export interface OutputObject {
    value: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ITimelock extends BaseContract {
  connect(runner?: ContractRunner | null): ITimelock;
  waitForDeployment(): Promise<this>;

  interface: ITimelockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  consumeValue: TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  consumeValuePreview: TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish],
    [boolean],
    "view"
  >;

  createAgreement: TypedContractMethod<
    [asset: AddressLike, beneficiary: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "consumeValue"
  ): TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "consumeValuePreview"
  ): TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "createAgreement"
  ): TypedContractMethod<
    [asset: AddressLike, beneficiary: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "AgreementClaimed"
  ): TypedContractEvent<
    AgreementClaimedEvent.InputTuple,
    AgreementClaimedEvent.OutputTuple,
    AgreementClaimedEvent.OutputObject
  >;
  getEvent(
    key: "AgreementCreated"
  ): TypedContractEvent<
    AgreementCreatedEvent.InputTuple,
    AgreementCreatedEvent.OutputTuple,
    AgreementCreatedEvent.OutputObject
  >;
  getEvent(
    key: "AgreementFrozen"
  ): TypedContractEvent<
    AgreementFrozenEvent.InputTuple,
    AgreementFrozenEvent.OutputTuple,
    AgreementFrozenEvent.OutputObject
  >;
  getEvent(
    key: "AgreementRescued"
  ): TypedContractEvent<
    AgreementRescuedEvent.InputTuple,
    AgreementRescuedEvent.OutputTuple,
    AgreementRescuedEvent.OutputObject
  >;
  getEvent(
    key: "TimeLockFrozen"
  ): TypedContractEvent<
    TimeLockFrozenEvent.InputTuple,
    TimeLockFrozenEvent.OutputTuple,
    TimeLockFrozenEvent.OutputObject
  >;

  filters: {
    "AgreementClaimed(uint256,address,address,uint256,address)": TypedContractEvent<
      AgreementClaimedEvent.InputTuple,
      AgreementClaimedEvent.OutputTuple,
      AgreementClaimedEvent.OutputObject
    >;
    AgreementClaimed: TypedContractEvent<
      AgreementClaimedEvent.InputTuple,
      AgreementClaimedEvent.OutputTuple,
      AgreementClaimedEvent.OutputObject
    >;

    "AgreementCreated(uint256,address,address,uint256,uint256)": TypedContractEvent<
      AgreementCreatedEvent.InputTuple,
      AgreementCreatedEvent.OutputTuple,
      AgreementCreatedEvent.OutputObject
    >;
    AgreementCreated: TypedContractEvent<
      AgreementCreatedEvent.InputTuple,
      AgreementCreatedEvent.OutputTuple,
      AgreementCreatedEvent.OutputObject
    >;

    "AgreementFrozen(uint256,bool)": TypedContractEvent<
      AgreementFrozenEvent.InputTuple,
      AgreementFrozenEvent.OutputTuple,
      AgreementFrozenEvent.OutputObject
    >;
    AgreementFrozen: TypedContractEvent<
      AgreementFrozenEvent.InputTuple,
      AgreementFrozenEvent.OutputTuple,
      AgreementFrozenEvent.OutputObject
    >;

    "AgreementRescued(uint256,address,address,uint256,address)": TypedContractEvent<
      AgreementRescuedEvent.InputTuple,
      AgreementRescuedEvent.OutputTuple,
      AgreementRescuedEvent.OutputObject
    >;
    AgreementRescued: TypedContractEvent<
      AgreementRescuedEvent.InputTuple,
      AgreementRescuedEvent.OutputTuple,
      AgreementRescuedEvent.OutputObject
    >;

    "TimeLockFrozen(bool)": TypedContractEvent<
      TimeLockFrozenEvent.InputTuple,
      TimeLockFrozenEvent.OutputTuple,
      TimeLockFrozenEvent.OutputObject
    >;
    TimeLockFrozen: TypedContractEvent<
      TimeLockFrozenEvent.InputTuple,
      TimeLockFrozenEvent.OutputTuple,
      TimeLockFrozenEvent.OutputObject
    >;
  };
}
