/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BaseProxyOFT__factory } from "./BaseProxyOFT__factory";
export { ERC20MintAndBurn__factory } from "./ERC20MintAndBurn__factory";
