/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { PermitRouter__factory } from "./PermitRouter__factory";
export { PermitRouterV2__factory } from "./PermitRouterV2__factory";
