/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from "./ERC20";
export type { ERC20Burnable } from "./ERC20Burnable";
export type { ERC20Pausable } from "./ERC20Pausable";
export type { IERC20 } from "./IERC20";
