/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as draftIerc20PermitSol from "./draft-IERC20Permit.sol";
export type { draftIerc20PermitSol };
export type { EIP712 } from "./EIP712";
export type { ERC20MinterBurnerPauserPermitForReplacement } from "./ERC20MinterBurnerPauserPermitForReplacement";
