/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BaseProxyOFT } from "./BaseProxyOFT";
export type { ERC20MintAndBurn } from "./ERC20MintAndBurn";
